# Generated by Django 4.2.4 on 2023-09-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team_data_modes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('mode1', 'scrape'), ('mode2', 'db')], default='default', max_length=10)),
            ],
        ),
    ]
