# Generated by Django 4.2.4 on 2023-09-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_team_data_modes_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_data_modes',
            name='mode',
            field=models.CharField(choices=[('scrape', 'scrape'), ('db', 'db')], default='db', max_length=10),
        ),
    ]
