# Generated by Django 4.2.4 on 2023-09-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_playerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='Born',
            field=models.CharField(max_length=255),
        ),
    ]
